//
//  RISReferenceType.swift
//  
//
//  Created by Jae Seung Lee on 10/17/21.
//

import Foundation

public enum RISReferenceType: String {
    case ABST // "Abstract"
    case ADVS // "Audiovisual material"
    case AGGR // "Aggregated Database"
    case ANCIENT // "Ancient Text"
    case ART // "Art Work"
    case BILL // "Bill"
    case BLOG // "Blog"
    case BOOK // "Whole book"
    case CASE // "Case"
    case CHAP // "Book chapter"
    case CHART // "Chart"
    case CLSWK // "Classical Work"
    case COMP // "Computer program"
    case CONF // "Conference proceeding"
    case CPAPER // "Conference paper"
    case CTLG // "Catalog"
    case DATA // "Data file"
    case DBASE // "Online Database"
    case DICT // "Dictionary"
    case EBOOK // "Electronic Book"
    case ECHAP // "Electronic Book Section"
    case EDBOOK // "Edited Book"
    case EJOUR // "Electronic Article"
    case WEB // "Web Page"
    case ENCYC // "Encyclopedia"
    case EQUA // "Equation"
    case FIGURE // "Figure"
    case GEN // "Generic"
    case GOVDOC // "Government Document"
    case GRANT // "Grant"
    case HEAR // "Hearing"
    case ICOMM // "Internet Communication"
    case INPR // "In Press"
    case JFULL // "Journal (full)"
    case JOUR // "Journal"
    case LEGAL // "Legal Rule or Regulation"
    case MANSCPT // "Manuscript"
    case MAP // "Map"
    case MGZN // "Magazine article"
    case MPCT // "Motion picture"
    case MULTI // "Online Multimedia"
    case MUSIC // "Music score"
    case NEWS // "Newspaper"
    case PAMP // "Pamphlet"
    case PAT // "Patent"
    case PCOMM // "Personal communication"
    case RPRT // "Report"
    case SER // "Serial publication"
    case SLIDE // "Slide"
    case SOUND // "Sound recording"
    case STAND // "Standard"
    case STAT // "Statute"
    case THES // "Thesis/Dissertation"
    case UNBILL // "Unenacted Bill"
    case UNPB // "Unpublished work"
    case VIDEO // "Video recording"
}
